Repository LIKELION-SWU-13th/likelion-13th-fe-session, pull requests merged in 2025-05, with the labels that each got.

#46 [5주차] 김유빈 과제 제출
  week05/.gitignore
  week05/README.md
  week05/package-lock.json
  week05/package.json
  week05/public/favicon.ico
  week05/public/happy.jpeg
  week05/public/index.html
  week05/public/manifest.json
  week05/public/robots.txt
  week05/public/sad.jpeg
  week05/src/App.css
  week05/src/App.js
  week05/src/components/cheer.jsx
  week05/src/components/luckyCheer.jsx
  week05/src/components/profile.jsx
  week05/src/index.css
  week05/src/index.js
Labels: 과제, 5주차

#47 [5주차] 정규은 과제 제출
  Week05/work5/.gitignore
  Week05/work5/README.md
  Week05/work5/package-lock.json
  Week05/work5/package.json
  Week05/work5/public/favicon.ico
  Week05/work5/public/index.html
  Week05/work5/public/manifest.json
  Week05/work5/public/profile.jpg
  Week05/work5/public/robots.txt
  Week05/work5/src/App.js
  Week05/work5/src/components/CardContainer.jsx
  Week05/work5/src/components/Diary.jsx
  Week05/work5/src/components/profile.jsx
  Week05/work5/src/index.css
  Week05/work5/src/index.js
Labels: 과제, 5주차

#50 [8주차] 주채빈 과제 제출
  week08/.gitignore
  week08/README.md
  week08/package-lock.json
  week08/package.json
  week08/public/index.html
  week08/public/manifest.json
  week08/public/robots.txt
  week08/src/App.js
  week08/src/Detail.js
  week08/src/Diary.css
  week08/src/Diary.js
  week08/src/DiaryContext.js
  week08/src/DiaryProvider.js
  week08/src/History.js
  week08/src/index.css
  week08/src/index.js
Labels: 과제, 8주차

#55 [8주차] 정규은 과제 제출
  Week08/project8/.gitignore
  Week08/project8/README.md
  Week08/project8/package-lock.json
  Week08/project8/package.json
  Week08/project8/public/favicon.ico
  Week08/project8/public/index.html
  Week08/project8/public/logo192.png
  Week08/project8/public/logo512.png
  Week08/project8/public/manifest.json
  Week08/project8/public/robots.txt
  Week08/project8/src/App.css
  Week08/project8/src/App.js
  Week08/project8/src/context/DiaryContext.jsx
  Week08/project8/src/index.css
  Week08/project8/src/index.js
  Week08/project8/src/pages/Detail.jsx
  Week08/project8/src/pages/History.jsx
  Week08/project8/src/pages/Home.jsx
Labels: 과제, 8주차

#49 [8주차] 김지원 과제 제출
  .DS_Store
  session5-2/.gitignore
  session5-2/README.md
  session5-2/package-lock.json
  session5-2/package.json
  session5-2/public/favicon.ico
  session5-2/public/index.html
  session5-2/public/manifest.json
  session5-2/public/robots.txt
  session5-2/src/Child.jsx
  session5-2/src/GrandParent.jsx
  session5-2/src/Parent.jsx
  session5-2/src/UserContext.jsx
  session5-2/src/index.css
  session5-2/src/index.js
  week08-1/.gitignore
  week08-1/README.md
  week08-1/package-lock.json
  week08-1/package.json
  week08-1/public/favicon.ico
  week08-1/public/index.html
  week08-1/public/logo192.png
  week08-1/public/logo512.png
  week08-1/public/manifest.json
  week08-1/public/robots.txt
  week08-1/src/App.css
  week08-1/src/App.js
  week08-1/src/DiaryContext.js
  week08-1/src/DiaryProvider.js
  week08-1/src/History.js
  week08-1/src/Home.js
  week08-1/src/index.css
  week08-1/src/index.js
  week5/.gitignore
  week5/README.md
  week5/package-lock.json
  week5/package.json
  week5/public/favicon.ico
  week5/public/index.html
  week5/public/manifest.json
  week5/public/robots.txt
  week5/src/App.css
  week5/src/App.js
  week5/src/Child.jsx
  week5/src/GrandParent.jsx
  week5/src/NoticeBox.jsx
  week5/src/Parent.jsx
  week5/src/index.css
  week5/src/index.js
Labels: 과제, 8주차

#60 [9주차] 손예원 과제 제출
  Week09/week09/.gitignore
  Week09/week09/README.md
  Week09/week09/package-lock.json
  Week09/week09/package.json
  Week09/week09/public/React App.html
  Week09/week09/public/React App_files/Netflix_2015_logo.svg
  Week09/week09/public/React App_files/bundle.js
  Week09/week09/public/background.jpg
  Week09/week09/public/favicon.ico
  Week09/week09/public/index.html
  Week09/week09/public/manifest.json
  Week09/week09/public/robots.txt
  Week09/week09/src/App.css
  Week09/week09/src/App.js
  Week09/week09/src/context/AuthContext.jsx
  Week09/week09/src/index.css
  Week09/week09/src/index.js
  Week09/week09/src/pages/HomePage.jsx
  Week09/week09/src/pages/LoginPage.css
  Week09/week09/src/pages/LoginPage.jsx
Labels: 과제, 9주차

#66 [10주차] 최영 과제 제출
  week10/.env
  week10/.gitignore
  week10/README.md
  week10/package-lock.json
  week10/package.json
  week10/public/favicon.ico
  week10/public/index.html
  week10/public/logo192.png
  week10/public/logo512.png
  week10/public/manifest.json
  week10/public/robots.txt
  week10/src/App.css
  week10/src/App.js
  week10/src/components/Header.css
  week10/src/components/Header.jsx
  week10/src/images/banner1.png
  week10/src/images/banner2.png
  week10/src/images/banner3.png
  week10/src/images/icon_search.svg
  week10/src/images/mainLogo.svg
  week10/src/images/profile.png
  week10/src/index.css
  week10/src/index.js
  week10/src/pages/Home.css
  week10/src/pages/Home.jsx
  week10/upload1.png
  week10/upload2.png
  week10/개발일지
Labels: 과제, 10주차

#68 [10주차] 손예원 과제 제출
  Week10/week10/.gitignore
  Week10/week10/README.md
  Week10/week10/package-lock.json
  Week10/week10/package.json
  Week10/week10/public/favicon.ico
  Week10/week10/public/index.html
  Week10/week10/public/manifest.json
  Week10/week10/public/robots.txt
  Week10/week10/src/App.js
  Week10/week10/src/components/ContentCard.js
  Week10/week10/src/components/ContentSection.js
  Week10/week10/src/components/Header.js
  Week10/week10/src/components/MainBanner.js
  Week10/week10/src/index.css
  Week10/week10/src/index.js
  Week10/week10/src/pages/HomePage.js
  Week10/week10/src/styles/App.css
  Week10/week10/src/styles/ContentCard.css
  Week10/week10/src/styles/ContentSection.css
  Week10/week10/src/styles/Header.css
  Week10/week10/src/styles/MainBanner.css
  Week10/week10/src/utils/api.js
Labels: 과제, 10주차

#69 [10주차] 김유빈 과제 제출
  week10/.gitignore
  week10/README.md
  week10/package-lock.json
  week10/package.json
  week10/public/banner1.webp
  week10/public/banner2.webp
  week10/public/banner3.webp
  week10/public/favicon.ico
  week10/public/index.html
  week10/public/logo.png
  week10/public/manifest.json
  week10/public/robots.txt
  week10/src/App.css
  week10/src/App.js
  week10/src/api/tmdb.jsx
  week10/src/components/BannerCarousel.css
  week10/src/components/BannerCarousel.jsx
  week10/src/components/ContentSection.css
  week10/src/components/ContentSection.jsx
  week10/src/components/Header.css
  week10/src/components/Header.jsx
  week10/src/components/Home.jsx
  week10/src/components/MovieCard.css
  week10/src/components/MovieCard.jsx
  week10/src/components/Slider.jsx
  week10/src/index.css
  week10/src/index.js
Labels: 과제, 10주차
