Repository LIKELION-SWU-13th/likelion-13th-fe-session, pull requests merged in 2025-04, with the labels that each got.

#25 [3주차] 김유빈 과제 제출
  Week03/index.html
  Week03/script.js
  Week03/style.css
Labels: 과제, 3주차

#19 [2-3주차] 주채빈 과제 제출
  .github/pull_request_template.md
  .gitignore
  README.md
  Week02/index.html
  Week02/photo.jpg
  Week02/style.css
  Week03/todo.css
  Week03/todo.html
  Week03/todo.js
Labels: 과제, 2주차, 3주차

#21 [3주차] 손예원 과제 제출
  Week03/Todo.html
  Week03/todo.css
Labels: 과제, 3주차

#28 [4주차] 최영 과제 제출
  week04/.gitignore
  week04/README.md
  week04/package-lock.json
  week04/package.json
  week04/public/index.html
  week04/public/manifest.json
  week04/public/robots.txt
  week04/src/App.css
  week04/src/App.js
  week04/src/assets/aa.jpg
  week04/src/assets/aaa.jpg
  week04/src/index.css
  week04/src/index.js
Labels: 과제, 4주차

#37 [4주차] 정규은 과제 제출
  Week04/myapp/.gitignore
  Week04/myapp/README.md
  Week04/myapp/package-lock.json
  Week04/myapp/package.json
  Week04/myapp/public/favicon.ico
  Week04/myapp/public/index.html
  Week04/myapp/public/manifest.json
  Week04/myapp/public/robots.txt
  Week04/myapp/src/App.css
  Week04/myapp/src/App.js
  Week04/myapp/src/index.css
  Week04/myapp/src/index.js
Labels: 과제, 4주차

#33 [4주차] 김유빈 과제 제출
  week04/.gitignore
  week04/README.md
  week04/package-lock.json
  week04/package.json
  week04/public/favicon.ico
  week04/public/index.html
  week04/public/manifest.json
  week04/public/robots.txt
  week04/src/App.css
  week04/src/App.js
  week04/src/index.css
  week04/src/index.js
Labels: 과제, 4주차

#30 [4주차] 김지원 과제 제출
  .DS_Store
  week04/.gitignore
  week04/README.md
  week04/package-lock.json
  week04/package.json
  week04/public/favicon.ico
  week04/public/index.html
  week04/public/manifest.json
  week04/public/robots.txt
  week04/src/App.css
  week04/src/App.js
  week04/src/index.css
  week04/src/index.js
Labels: 과제, 4주차

#39 [5주차] 손예원 과제 제출
  week05/.gitignore
  week05/README.md
  week05/package-lock.json
  week05/package.json
  week05/public/favicon.ico
  week05/public/index.html
  week05/public/manifest.json
  week05/public/robots.txt
  week05/src/App.js
  week05/src/components/Footer.jsx
  week05/src/components/Greeting.jsx
  week05/src/components/profile.jsx
  week05/src/index.css
  week05/src/index.js
Labels: 과제, 5주차

#40 [5주차] 송지은 과제 제출
  Week05/package-lock.json
  Week05/week05/.gitignore
  Week05/week05/README.md
  Week05/week05/package-lock.json
  Week05/week05/package.json
  Week05/week05/public/favicon.ico
  Week05/week05/public/index.html
  Week05/week05/public/jieun.png
  Week05/week05/public/manifest.json
  Week05/week05/public/robots.txt
  Week05/week05/src/App.js
  Week05/week05/src/components/diary.jsx
  Week05/week05/src/components/fighting.jsx
  Week05/week05/src/components/profile.jsx
  Week05/week05/src/index.css
  Week05/week05/src/index.js
Labels: 과제, 5주차

#41 [5주차] 김지원 과제 제출
  week05session5/.gitignore
  week05session5/.vscode/launch.json
  week05session5/README.md
  week05session5/package-lock.json
  week05session5/package.json
  week05session5/public/favicon.ico
  week05session5/public/happy.png
  week05session5/public/happy2.png
  week05session5/public/index.html
  week05session5/public/manifest.json
  week05session5/public/robots.txt
  week05session5/public/sad.png
  week05session5/public/sad2.png
  week05session5/src/App.js
  week05session5/src/components/MoodImage.jsx
  week05session5/src/components/MoodText.jsx
  week05session5/src/components/Quote.jsx
  week05session5/src/components/Title.jsx
  week05session5/src/components/profile.jsx
  week05session5/src/index.css
  week05session5/src/index.js
Labels: 과제, 5주차
